### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.lexaloffle/pico-8/config.txt'

### ISSUE THREAD

**Issue by arthurlutz** [franciscod/p8dl#1]
```
# p8dl 
need a cart-id as argument! (for example, 10022 gets you Hug Arena)
# p8dl 10022
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/p8dl/bin/p8dl", line 10, in <module>
    sys.exit(main())
  File "/home/arthur/.virtualenvs/p8dl/lib/python3.6/site-packages/p8dl/cli.py", line 12, in main
    path, httpmsg = cartretrieve(cart_id)
  File "/home/arthur/.virtualenvs/p8dl/lib/python3.6/site-packages/p8dl/downloader.py", line 37, in cartretrieve
    url, path = cart_url(cart_id), cart_path(cart_id)
  File "/home/arthur/.virtualenvs/p8dl/lib/python3.6/site-packages/p8dl/downloader.py", line 31, in cart_path
    pico8_config_var('root_path'),
  File "/home/arthur/.virtualenvs/p8dl/lib/python3.6/site-packages/p8dl/downloader.py", line 23, in pico8_config_var
    with open(os.path.join(pico8_path(), 'config.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/arthur/.lexaloffle/pico-8/config.txt'
```

Would there be a way to work without this configuration file ? Or a way to create it ?

**Comment by franciscod** [comment]
Yes, definitely should download the file anyway (the working directory being the target candidate).

This was made before splore was a thing and maybe it's not too useful anymore... have you checked that out? Is this still useful? :)
